Busy pin initialisation and T-Beam S3 Core/Supreme pinmap
TristanWebber/arduino-lmic pull request #1
Opened 2024-05-25 07:48 UTC by oseiler2

Added pinMode initialisation for busy pin if configured
Added pinmap for TTGO T-Beam S3 core/supreme

2024-06-25 00:58 UTC, TristanWebber requested changes
Looks good - Thanks. I have:
- Cross referenced the pinmap for ttgo_tbeam_s3 and it looks fine
- Agree with the proposal to set the busy pinMode in the hal_io_init() function, although have recommended a change to the queryBusyPin() virtual function declaration in a different file.

I tested that this still compiles for 126x and 127x configurations and it all seems fine.

2024-06-25 00:58 UTC, TristanWebber commented on src/hal/hal.cpp
@oseiler2 - Sorry that a week turned in to a month...

This mostly looks fine but I'm thinking we take an alternative approach by avoiding the `#if` macro and adopting the style of the rest of the codebase.

Can you please:
- In file `src/arduino_lmic_hal_configuration.h`, amend line 93 to return `HalPinmap_t::LMIC_UNUSED_PIN` instead of `0`
- Then in this file `src/hal/hal.cpp` you will be able to use the same pattern as the other pinMode calls in this file:
```cpp
if (pHalConfig->queryBusyPin() != LMIC_UNUSED_PIN) {
        pinMode(pHalConfig->queryBusyPin(), INPUT);
}

Are you happy with that approach?
```

2024-06-26 06:12 UTC, oseiler2 commented on src/hal/hal.cpp
Fair call, all done.

2024-06-26 08:58 UTC, TristanWebber approved these changes
Thanks for that!

2024-06-26 08:58 UTC, merged